name: Magic Number Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect_magic_numbers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Run go-mnd
        uses: actions/go-mnd@v1
